### ISSUE TITLE
Don't allow the buttons at the bottom of the chat window to wrap onto two lines.

### ISSUE THREAD

**Issue by tehdragonfly** [MSPARP/newparp#26]
The new settings button means these buttons wrap on mobile.

**Comment by nadiaff** [comment]
Character Settings: http://fortawesome.github.io/Font-Awesome/icon/users/
User list; http://fortawesome.github.io/Font-Awesome/icon/list-ul/
Settings: http://fortawesome.github.io/Font-Awesome/icon/cog/
