### ISSUE TITLE
Needs More Character Limit

### ISSUE THREAD

**Issue by GamzeeMabara** [MSPARP/newparp#29]
Apparently, you can currently fit the entire contents of a novel into one post/the chat description. Even if we have the read more for longer posts, I don't think it's a good idea to allow someone to post so much text that they crash the server/lag the chat (the latter seems to be what happened when Idler posted all of 3 books in one chat.).

* Decide on a length for topics and posts
* Decide on the length before a read more
* Drink coffee

**Comment by GamzeeMabara** [comment]
TOPIC: 500 characters
POSTS, DESCRIPTIONS, RULES: 5,000 Characters.
READMORE: After 10 lines.

**Comment by tehdragonfly** [comment]
Messages, topics and ban reasons are done, description and rules are still to do. Coffee is a WONTFIX.

**Comment by GamzeeMabara** [comment]
Amend the coffee bug to 'BEVERAGE OF CHOICE'.
