### ISSUE TITLE
Text commands

### ISSUE THREAD

**Issue by tehdragonfly** [MSPARP/newparp#3]
Current progress:
* Actions (/me)
* Topics (/topic)
* User groups (/set # group)
* Kicking (/kick #)
* Banning (/ban # reason)

Apparently there's a full list somewhere so that needs reviewing.

**Comment by nadiaff** [comment]
Default character quirk and color text commands:

e.g. /equius or /vriska changes your text to their quirk and colors

**Comment by tehdragonfly** [comment]
Closing because if we haven't thought of any in 6 months it can't be that important. Feel free to open more issues if there are more that are needed.
