### ISSUE TITLE
Invisible chats + Public groups

### ISSUE THREAD

**Issue by GamzeeMabara** [MSPARP/newparp#30]
Right now, it is possible to make a chat consisting of only underscores. Doing so causes the public function to be messed up, as it appears that there is no chat there. You can't tell how many underscores the chat consists of, so  one undescore and ten look like the same chat. Also, I am not sure if this is related to the issue, but there is [a random white bar at the bottom of the group chat](http://i.gyazo.com/31aa7cc5a850dc69663ed6cd56ecadc6.png) page as well. You can also see the underscore chat problem there.

Solutions? Either make it impossible to make a chat that consists only of underscores, or make underscores visible in the public groups _only_ if there is just underscores.These changes should also apply to the name preview in the topbar.

**Comment by tehdragonfly** [comment]
The white line is a glitch with Chrome's column rendering so there isn't much we can do about that.

With underscores I'm leaning towards making underscores visible in the public groups _only_ if there is just underscores.
