### ISSUE TITLE
Shortcuts for temporarily switching character

### ISSUE THREAD

**Issue by nadiaff** [MSPARP/newparp#36]
Wrap around auto-quirking + colors 

e.g. text in [vriska] [/vriska] will have her cerulean color and quirks

**Comment by tehdragonfly** [comment]
This should use /name like text commands rather than BBCode, and also apply to saved characters too: http://blog.msparp.com/post/114008861504

**Comment by tehdragonfly** [comment]
This is now done for user-created characters.

**Comment by tehdragonfly** [comment]
Apparently this isn't needed for search characters, so closing for now.
