### ISSUE TITLE
Quirks should ignore links and bbcode

### ISSUE THREAD

**Issue by nadiaff** [MSPARP/newparp#39]
I dunno. Is this a bug or an enhancement?

**Comment by nadiaff** [comment]
Maybe through regexp magic. Must ask epi.

**Comment by tehdragonfly** [comment]
This is gonna be hard to do for real, so a half-solution for now is to add extra replacements to canon quirks to undo the quirks inside bbcode tags, eg. [2up] to [sup] for Sollux.

**Comment by tehdragonfly** [comment]
Quirks are now dropped when a message starts with a link, which helps this somewhat (be978d9).

**Comment by epithetic** [comment]
somewhat mitigated through safe BBcode, tentatively closing
