### ISSUE TITLE
BBCode

### ISSUE THREAD

**Issue by tehdragonfly** [MSPARP/newparp#6]
* ~~[i] - italics~~
* ~~[u] - underline~~
* ~~[del] - strikethrough~~
* ~~[sup] - superscript~~
* ~~[sub] - subscript~~
* ~~[url]~~
* ~~[spoiler] - spoiler~~
* ~~[br]~~

**Comment by tehdragonfly** [comment]
* [font]
* [color]
* [bgcolor]
* [tshadow] (globals only)
* [bshadow] (globals only)

**Comment by nadiaff** [comment]
Filter out javascript on [url], don't allow people to embed spoiler in url (or is it vice versa??)
