### ISSUE TITLE
Spamless Silencing False Spam

### ISSUE THREAD

**Issue by GamzeeMabara** [MSPARP/newparp#86]
Spamless reads messages across all chats at once, which means it may silence someone for sending the same message that was spammed in another chat. 

For example, if a john spammed NO in one chat, but he was the creator so he couldn't be silenced, someone in another chat could say NO and then be silenced. This happens because spamless continues holding the spam creators do in its warn system, and they have spammed as much as it normally takes to silence a normal user. So, when it sees someone who can be silenced, it silences them.

**Comment by tehdragonfly** [comment]
There's also a Trello card for this.

**Comment by GamzeeMabara** [comment]
Oops, my b.
