### ISSUE TITLE
Put options for modding/unmodding/etc. on chat users pages

### ISSUE THREAD

**Issue by tehdragonfly** [MSPARP/newparp#9]

**Comment by tehdragonfly** [comment]
Should these options only be visible to site admins or mods in general? I say yes but @GamzeeMabara thinks it would make it too easy for rogue mods to abuse.

**Comment by nadiaff** [comment]
I suggest we only make it available to site admins and chat owners for now. If there is a demand for it to be made available to general mods, we could consider it.

**Comment by tehdragonfly** [comment]
This uses the chat API, which means that if you're not in the chat when you use the dropdowns then you get marked as online and timed out a few seconds later.
